# Generated by Django 2.2.7 on 2019-11-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.CharField(max_length=9000),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.CharField(max_length=9000, null=True),
        ),
    ]
