# Generated by Django 2.2.5 on 2019-09-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190921_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.FloatField(default=0.0),
        ),
    ]
