# Generated by Django 2.2.6 on 2019-10-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190927_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-title',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
