# Generated by Django 2.2.6 on 2019-11-10 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20191013_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=90)),
                ('city', models.CharField(max_length=120)),
                ('card_name', models.CharField(max_length=200, null=True)),
                ('card_number', models.CharField(max_length=18, null=True)),
                ('expiring_month', models.DateField(null=True)),
                ('expiring_year', models.DateField(null=True)),
                ('card_cvv', models.CharField(max_length=3, null=True)),
                ('product', models.ForeignKey(on_delete=True, to='core.Product')),
                ('user', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
